### PR TITLE
Run ocamlformat on WP

### PR DESCRIPTION
**Pull request by fortunac**
- `ocamlformat` should be installed with `opam install ocamlformat`
- You can format your code with `make format`

### CODE REVIEW

**Comment by codyroux** [comment]
I'm all for this, with the minor caveat that I prefer the docstrings to appear before rather than after a function definition in the `.mli`.

Major caveat: it looks like you have some changes which are *not* a simple application of the code formatter. These should be part of a separate (and much easier to approve) PR.

**Comment by fortunac** [comment]
> I'm all for this, with the minor caveat that I prefer the docstrings to appear before rather than after a function definition in the `.mli`.
> 
> Major caveat: it looks like you have some changes which are _not_ a simple application of the code formatter. These should be part of a separate (and much easier to approve) PR.

I was able to figure out the config that places docstrings before function definitions, and added it to the `.ocamlformat` files. I also removed the result of running the formatter from this PR.

**Comment by ivg** [comment]
I would advise against using ocamlformat as the style that it enforces is pretty destructive to monadic operations, e.g., see how it destroys Core Theory implementation to [an unreadable mess][1] see [core_theory_basic.ml][2] as a particular example. 
```
  let loadw out dir mem key =
    dir                                  (* <--- o_O *)
    >>= fun dir ->
    mem
    >>-> fun ms mem ->
    key
    >>= fun key ->
    let vs = Mem.vals ms in
    let chunk_size = size vs in
    let needed = size out in
    let rec loop chunks loaded =
      if loaded < needed then
        let key = nsucc !!key (loaded / chunk_size) in
        bind (load !!mem key)
        @@ fun chunk -> loop (var chunk :: chunks) (loaded + chunk_size)
      else ite !!dir (concat out (List.rev chunks)) (concat out chunks) in
    loop [] 0
```

See also https://github.com/BinaryAnalysisPlatform/bap/issues/1149

[1]: https://github.com/BinaryAnalysisPlatform/bap/compare/master...ivg:ocamlformatted-compact
[2]: https://github.com/ivg/bap/blob/40412630d50b8cccdb138bf63aee86b2e717f90f/lib/bap_core_theory/bap_core_theory_basic.ml#L55

**Comment by fortunac** [comment]
> I would advise against using ocamlformat as the style that it enforces is pretty destructive to monadic operations, e.g., see how it tunrs the Core Theory implementation to [an unreadable mess](https://github.com/BinaryAnalysisPlatform/bap/compare/master...ivg:ocamlformatted-compact) see [core_theory_basic.ml](https://github.com/ivg/bap/blob/40412630d50b8cccdb138bf63aee86b2e717f90f/lib/bap_core_theory/bap_core_theory_basic.ml#L55) as a particular example.
> 
> ```
>   let loadw out dir mem key =
>     dir                                  (* <--- o_O *)
>     >>= fun dir ->
>     mem
>     >>-> fun ms mem ->
>     key
>     >>= fun key ->
>     let vs = Mem.vals ms in
>     let chunk_size = size vs in
>     let needed = size out in
>     let rec loop chunks loaded =
>       if loaded < needed then
>         let key = nsucc !!key (loaded / chunk_size) in
>         bind (load !!mem key)
>         @@ fun chunk -> loop (var chunk :: chunks) (loaded + chunk_size)
>       else ite !!dir (concat out (List.rev chunks)) (concat out chunks) in
>     loop [] 0
> ```
> 
> See also [BinaryAnalysisPlatform/bap#1149](https://github.com/BinaryAnalysisPlatform/bap/issues/1149)

Thanks for the head up, Ivan! I didn't realize ocamlformat could be destructive to monads. Judging from the linked issue, ocamlformat isn't ready for use. We'll close this PR for now.

**Pull request closed without merging**
